### PR TITLE
Adding 3 community plugins

### PR DESCRIPTION
**Pull request by DebacManikandan-DEFEND**
We have developed and uploaded the following 3 plugins:
1. IP Quality Score
2. IP Geo Location
3. Have I Been Pwned

Each plugin has its own folder with the manifest (yaml) and README file in it. We have also added screenshots of the plugins in the Images folder inside Community Plugins directory. This will be used in the README files for reference.

### CODE REVIEW

**Comment by DebacManikandan-DEFEND** [comment]
@microsoft-github-policy-service agree company="DEFEND"

**Comment by KwachSean** [comment]
@DebacManikandan-DEFEND please include OpenAI spec file within the Github commit

**Comment by DebacManikandan-DEFEND** [comment]
Hey @KwachSean - the OpenAPI files have been added, and the OpenAPISpecURL in the manifest files have been updated as well :)

**Comment by DebacManikandan-DEFEND** [comment]
Hey @KwachSean - do we have any updates on the PR? :)

**Comment by DebacManikandan-DEFEND** [comment]
Abandoning this pull request to split th above into 3 separate pull requests.

**Comment by marioncole-ms** [comment]
I have checked all 3 manifests.  Each has 1 GET Skill.  No POST Skill.  Tested in CfS, and all were successful.

Validation Passed.

**Comment by DebacManikandan-DEFEND** [comment]
Awesome.  Thank you so much Marion 😊


Ngā mihi,

Debac Manikandan | Senior Cybersecurity Engineer | +64 22 687 8855 | DEFEND

________________________________

**Pull request closed without merging**
